
/*
 * Query Purpose: Track medical device implantations and subsequent procedures
 * This query identifies patients with specific implantable pulse generators (IPGs)
 * and tracks either replacement/removal procedures or end of observation period
 */
 
with Device AS(
-- Activa PC
SELECT
	de.PERSON_ID,
	p.BIRTH_DATETIME,
	DATEDIFF(YEAR, BIRTH_DATETIME, DEVICE_EXPOSURE_START_DATE) - 
	CASE
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) < MONTH(BIRTH_DATETIME) THEN 1
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) = MONTH(BIRTH_DATETIME) AND DAY(DEVICE_EXPOSURE_START_DATE) < DAY(BIRTH_DATETIME) THEN 1
		ELSE 0
	END AS AGE_AT_IMPLANT,
	p.GENDER_SOURCE_VALUE,
	de.DEVICE_EXPOSURE_ID,
	de.DEVICE_SOURCE_VALUE,
	'Activa PC' AS DEVICE_NAME,
	de.DEVICE_EXPOSURE_START_DATE,
	de.DEVICE_EXPOSURE_END_DATE,
	ROW_NUMBER() OVER(
		PARTITION BY de.PERSON_ID
		ORDER BY de.DEVICE_EXPOSURE_START_DATE
	) AS RN
FROM @databaseschema.DEVICE_EXPOSURE de
JOIN @databaseschema.PERSON p
	ON p.PERSON_ID = de.PERSON_ID
WHERE de.DEVICE_SOURCE_VALUE like '%H3301106%' --Activa PC
OR de.DEVICE_SOURCE_CONCEPT_ID = '42087050'
OR de.DEVICE_CONCEPT_ID = '42087050'
	
UNION ALL

-- Vercise PC
SELECT
	de.PERSON_ID,
	p.BIRTH_DATETIME,
	DATEDIFF(YEAR, BIRTH_DATETIME, DEVICE_EXPOSURE_START_DATE) - 
	CASE
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) < MONTH(BIRTH_DATETIME) THEN 1
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) = MONTH(BIRTH_DATETIME) AND DAY(DEVICE_EXPOSURE_START_DATE) < DAY(BIRTH_DATETIME) THEN 1
		ELSE 0
	END AS AGE_AT_IMPLANT,
	p.GENDER_SOURCE_VALUE,
	de.DEVICE_EXPOSURE_ID,
	de.DEVICE_SOURCE_VALUE,
	'Vercise PC' AS DEVICE_NAME,
	de.DEVICE_EXPOSURE_START_DATE,
	de.DEVICE_EXPOSURE_END_DATE,
	ROW_NUMBER() OVER(
		PARTITION BY de.PERSON_ID
		ORDER BY de.DEVICE_EXPOSURE_START_DATE
	) AS RN
FROM @databaseschema.DEVICE_EXPOSURE de
JOIN @databaseschema.PERSON p
	ON p.PERSON_ID = de.PERSON_ID
WHERE de.DEVICE_SOURCE_VALUE like '%H3301027%' --Vercise PC
OR de.DEVICE_SOURCE_CONCEPT_ID = '42102989'
OR de.DEVICE_CONCEPT_ID = '42102989'

UNION ALL

--Infinity
SELECT
	de.PERSON_ID,
	p.BIRTH_DATETIME,
	DATEDIFF(YEAR, BIRTH_DATETIME, DEVICE_EXPOSURE_START_DATE) - 
	CASE
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) < MONTH(BIRTH_DATETIME) THEN 1
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) = MONTH(BIRTH_DATETIME) AND DAY(DEVICE_EXPOSURE_START_DATE) < DAY(BIRTH_DATETIME) THEN 1
		ELSE 0
	END AS AGE_AT_IMPLANT,
	p.GENDER_SOURCE_VALUE,
	de.DEVICE_EXPOSURE_ID,
	de.DEVICE_SOURCE_VALUE,
	'Infinity' AS DEVICE_NAME,
	de.DEVICE_EXPOSURE_START_DATE,
	de.DEVICE_EXPOSURE_END_DATE,
	ROW_NUMBER() OVER(
		PARTITION BY de.PERSON_ID
		ORDER BY de.DEVICE_EXPOSURE_START_DATE
	) AS RN
FROM @databaseschema.DEVICE_EXPOSURE de
JOIN @databaseschema.PERSON p
	ON p.PERSON_ID = de.PERSON_ID
WHERE de.DEVICE_SOURCE_VALUE like '%H3301109%' --Infinity
OR de.DEVICE_SOURCE_CONCEPT_ID = '42094394'
OR de.DEVICE_CONCPET_ID = '42094394'

UNION ALL

-- Soletra
SELECT
	de.PERSON_ID,
	p.BIRTH_DATETIME,
	DATEDIFF(YEAR, BIRTH_DATETIME, DEVICE_EXPOSURE_START_DATE) - 
	CASE
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) < MONTH(BIRTH_DATETIME) THEN 1
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) = MONTH(BIRTH_DATETIME) AND DAY(DEVICE_EXPOSURE_START_DATE) < DAY(BIRTH_DATETIME) THEN 1
		ELSE 0
	END AS AGE_AT_IMPLANT,
	p.GENDER_SOURCE_VALUE,
	de.DEVICE_EXPOSURE_ID,
	de.DEVICE_SOURCE_VALUE,
	'Soletra' AS DEVICE_NAME,
	de.DEVICE_EXPOSURE_START_DATE,
	de.DEVICE_EXPOSURE_END_DATE,
	ROW_NUMBER() OVER(
		PARTITION BY de.PERSON_ID
		ORDER BY de.DEVICE_EXPOSURE_START_DATE
	) AS RN
FROM @databaseschema.DEVICE_EXPOSURE de
JOIN @databaseschema.PERSON p
	ON p.PERSON_ID = de.PERSON_ID
WHERE de.DEVICE_SOURCE_VALUE like '%H3301006%' --Soletra
OR de.DEVICE_SOURCE_CONCEPT_ID = '42100618'
OR de.DEVICE_CONCEPT_ID = '42100618'

UNION ALL

-- Activa SC
SELECT
	de.PERSON_ID,
	p.BIRTH_DATETIME,
	DATEDIFF(YEAR, BIRTH_DATETIME, DEVICE_EXPOSURE_START_DATE) - 
	CASE
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) < MONTH(BIRTH_DATETIME) THEN 1
		WHEN MONTH(DEVICE_EXPOSURE_START_DATE) = MONTH(BIRTH_DATETIME) AND DAY(DEVICE_EXPOSURE_START_DATE) < DAY(BIRTH_DATETIME) THEN 1
		ELSE 0
	END AS AGE_AT_IMPLANT,
	p.GENDER_SOURCE_VALUE,
	de.DEVICE_EXPOSURE_ID,
	de.DEVICE_SOURCE_VALUE,
	'Activa SC' AS DEVICE_NAME,
	de.DEVICE_EXPOSURE_START_DATE,
	de.DEVICE_EXPOSURE_END_DATE,
	ROW_NUMBER() OVER(
		PARTITION BY de.PERSON_ID
		ORDER BY de.DEVICE_EXPOSURE_START_DATE
	) AS RN
FROM @databaseschema.DEVICE_EXPOSURE de
JOIN @databaseschema.PERSON p
	ON p.PERSON_ID = de.PERSON_ID
WHERE de.DEVICE_SOURCE_VALUE like '%H3301206%' --Activa SC
OR de.DEVICE_SOURCE_CONCEPT_ID = '42087056'
OR de.DEVICE_CONCEPT_ID = '42087056'
	
),

-- Filter to first device only for adult patients (18+)
CombineDevice AS(
SELECT * 
FROM Device
WHERE RN = 1 AND AGE_AT_IMPLANT >= 18
),

-- Find the first procedure (replacement/removal) after device implantation
RankedProc AS(
SELECT 
	ipg.PERSON_ID,
	BIRTH_DATETIME,
	AGE_AT_IMPLANT,
	GENDER_SOURCE_VALUE,
	DEVICE_EXPOSURE_ID,
	DEVICE_NAME,
	DEVICE_SOURCE_VALUE,
	DEVICE_EXPOSURE_START_DATE,
	DEVICE_EXPOSURE_END_DATE,
	PROCEDURE_DATE,
	PROCEDURE_CONCEPT_ID,
	c.CONCEPT_NAME,
	ROW_NUMBER() OVER(
		PARTITION BY device_exposure_id
		ORDER BY po.PROCEDURE_DATE ASC
	) AS RN,
	'1' AS EVENT_FLAG,
	DATEDIFF(DAY, DEVICE_EXPOSURE_START_DATE, PROCEDURE_DATE) AS FOLLOW_UP_DAYS
FROM CombineDevice ipg
JOIN @databaseschema.PROCEDURE_OCCURRENCE po
ON ipg.PERSON_ID = po.PERSON_ID
AND DEVICE_EXPOSURE_START_DATE < procedure_date
JOIN @databaseschema.CONCEPT c 
ON c.concept_id = po.PROCEDURE_CONCEPT_ID
WHERE PROCEDURE_CONCEPT_ID IN (4066681, 4087744, 4130819, 4193790, 4249002, 4262290, 4318831, 4336305, 37396722) ------ 각 기관에 맞게 outcome 정의 추가 (IPG 교체/제거 관련 outcome 코드)
),

-- For patients without procedures, find their last visit date (end of observation)
RankedObs AS (
SELECT
	ipg.PERSON_ID,
	BIRTH_DATETIME,
	AGE_AT_IMPLANT,
	GENDER_SOURCE_VALUE,
	DEVICE_EXPOSURE_ID,
	DEVICE_NAME,
	DEVICE_SOURCE_VALUE,
	DEVICE_EXPOSURE_START_DATE,
	DEVICE_EXPOSURE_END_DATE,
	VISIT_END_DATE AS PROCEDURE_DATE,
	'0' AS PROCEDURE_CONCEPT_ID,
	'End of Observation' AS CONCEPT_NAME,
	ROW_NUMBER() OVER(
		PARTITION BY device_exposure_id
		ORDER BY vo.VISIT_END_DATE DESC
	) AS RN,
	'0' AS EVENT_FLAG,
	DATEDIFF(DAY, DEVICE_EXPOSURE_START_DATE, VISIT_END_DATE) AS FOLLOW_UP_DAYS
FROM CombineDevice ipg
JOIN @databaseschema.VISIT_OCCURRENCE vo
ON ipg.PERSON_ID = vo.PERSON_ID
AND DEVICE_EXPOSURE_START_DATE <= vo.VISIT_END_DATE
WHERE NOT EXISTS(
	SELECT *
	FROM @databaseschema.PROCEDURE_OCCURRENCE po
	WHERE po.PERSON_ID = ipg.PERSON_ID
	AND ipg.DEVICE_EXPOSURE_START_DATE < po.PROCEDURE_DATE
	AND PROCEDURE_CONCEPT_ID IN (4066681, 4087744, 4130819, 4193790, 4249002, 4262290, 4318831, 4336305, 37396722)) ---
),

-- Combine patients with procedures and those with end of observation
CombinedResults AS(
	SELECT * FROM RankedProc WHERE RN = 1 -- First procedure after implant
	UNION ALL 
	SELECT * FROM RankedObs WHERE RN = 1 -- Last visit for patients without procedures
)

-- Final ouput: One row per device with either procedure or end of observation
SELECT *
FROM CombinedResults;
